### ISSUE TITLE
ExImage: Please update experiment names in “Expression Values” button

### ISSUE THREAD

**Issue by nanettec** [PlantGenIE/PlantGenIE#28]
When you view and download expression values in ExImage (EucGenIE), please update the experiment names in E. grandis x E. urophylla exAtlas, E. grandis Tissue exAtlas and Biotic Interactions. See uploaded file (update.txt).

[update.txt](https://github.com/PlantGenIE/PlantGenIE/files/2763166/update.txt)

**Comment by irusri** [comment]
Thanks Nanette! this has been fixed. If you are satisfied please close the issue.
