### ISSUE TITLE
Pfam domain

### ISSUE THREAD

**Issue by hui-liu** [PlantGenIE/PlantGenIE#56]
Display Pfam domain for protein gene

**Comment by hui-liu** [comment]
A specific Pfam domain may occur more than once. We did visualize the pram domain in "Functional", but we can't see the duplicated domain along with a sequence. Can we fix this problem?

<img width="846" alt="pfam" src="https://user-images.githubusercontent.com/10741007/53021300-32c4c200-3459-11e9-9da2-cf77fb161859.png">


```
XS01G0001800.1  ecae8fea0fec3c1f1e8c463712b1d3aa        1637    Pfam    PF00664 ABC transporter transmembrane region    321     586
XS01G0001800.1  ecae8fea0fec3c1f1e8c463712b1d3aa        1637    Pfam    PF00664 ABC transporter transmembrane region    953     1190
XS01G0001800.1  ecae8fea0fec3c1f1e8c463712b1d3aa        1637    Pfam    PF00005 ABC transporter 651     785
XS01G0001800.1  ecae8fea0fec3c1f1e8c463712b1d3aa        1637    Pfam    PF00005 ABC transporter 1280    1428
```

**Comment by irusri** [comment]
What do you think about this solution: http://g.recordit.co/1nU4GHmhQw.gif this is apart from the functional annotation tab.

**Comment by irusri** [comment]
Now its open in new page :)
