### ISSUE TITLE
Don't reload the network if the threshold isn't changed

### ISSUE THREAD

**Issue by maehler** [PlantGenIE/PlantGenIE#81]
The current behaviour is that whenever the threshold slider is touched, the network is reloaded, regardless of whether the threshold changed or not. This can be quite annoying if you have a big network that takes some time to load. I would suggest that if the slider is moved, but the threshold isn't actually changed, the network should not update.

**Comment by irusri** [comment]
Fixed!

**Comment by maehler** [comment]
Just a minor thing, but if *you* fix the issue, you shouldn't assign *me* to it. The person assigned to the issue is the one who is supposed to take care of it. 😃
