### ISSUE TITLE
Threshold issue when switching networks

### ISSUE THREAD

**Issue by maehler** [PlantGenIE/PlantGenIE#82]
I have a *P. tremula* v2.2 genelist that results in a fully connected cluster in AspWood (you can find the genelist at the bottom). In AspWood I see one bigger connected component. Saving this connected component as a new genelist and loading the AspLeaf network results in 5 connected components, but I would expect to see a single connected component.

## Steps to reproduce

1. Load the genelist into PlantGenIE using *P. tremula* v2.2.
2. Go to exNet.
3. Select AspWood.
4. Set the p-value threshold to 10^-2. You should now see a single connected component.
5. Change the network to AspLeaf.
6. You should now see two connected components in this view: one with two genes and one with 67 genes. Select the 67-gene component and create a new genelist.
7. The freshly loaded network now contains 5 distinct connected components, and a handful of genes without any connections. The expectation here would be that all the genes form a single connected component since the network and the threshold is the same as in the previous view.

This seems to have something to do with the threshold not updating properly when switching networks. After step 5 above, instead of creating a new genelist, I click the threshold slider without actually changing the threshold, the view updates with a different network structure. I am guessing that the underlying threshold somehow changes, but this is never presented to the user. See the video below for a short demonstration of the issue.

https://user-images.githubusercontent.com/2573608/114019069-42d4d100-986e-11eb-888c-53f5a2b6e909.mp4

## Genelist

```
Potra2n1c101, Potra2n1c142, Potra2n1c567, Potra2n1c923, Potra2n1c2214,
Potra2n1c2288, Potra2n1c2356, Potra2n1c2511, Potra2n1c2942, Potra2n1c3161,
Potra2n1c3736, Potra2n10c20260, Potra2n10c20628, Potra2n10c20641, Potra2n10c20846,
Potra2n10c21150, Potra2n10c21695, Potra2n11c22470, Potra2n11c23322, Potra2n12c24031,
Potra2n12c24202, Potra2n12c24927, Potra2n13c25185, Potra2n13c25579, Potra2n13c25771,
Potra2n13c25852, Potra2n14c26860, Potra2n14c27365, Potra2n15c28656, Potra2n15c28707,
Potra2n15c28801, Potra2n16c29503, Potra2n16c29689, Potra2n16c30487, Potra2n16c30499,
Potra2n16c30563, Potra2n17c31100, Potra2n17c31123, Potra2n17c31220, Potra2n18c33107,
Potra2n19c33482, Potra2n19c33823, Potra2n19c34193, Potra2n2c4070, Potra2n2c4468,
Potra2n2c4592, Potra2n2c4738, Potra2n2c5954, Potra2n2c6027, Potra2n2c6365,
Potra2n3c7779, Potra2n3c7951, Potra2n3c8097, Potra2n4c8567, Potra2n4c8773,
Potra2n4c9741, Potra2n4c10306, Potra2n5c10575, Potra2n5c10750, Potra2n5c10979,
Potra2n5c11241, Potra2n5c11814, Potra2n5c11816, Potra2n5c11923, Potra2n5c12554,
Potra2n5c12603, Potra2n6c12962, Potra2n6c13326, Potra2n6c13736, Potra2n6c13850,
Potra2n6c14119, Potra2n6c14415, Potra2n6c14653, Potra2n6c14886, Potra2n6c15317,
Potra2n7c15462, Potra2n7c15470, Potra2n7c15949, Potra2n7c16217, Potra2n8c17171,
Potra2n8c17317, Potra2n9c18672, Potra2n9c18760, Potra2n9c19051, Potra2n9c19431,
Potra2n197s34897, Potra2n636s36238, Potra2n7c15465
```

**Comment by maehler** [comment]
As a side note, I think that this issue actually prevents me from recording a new video for teaching next week, so it would be great if this could be fixed within the coming days. It is of course possible to record a video, but I'm afraid that the confusion that this issue would cause would make the assignment much less meaningful.

**Comment by irusri** [comment]
Can you try once more it should not update unless we change the threshold number?
https://recordit.co/yCItXNMfFF/gif/notify

**Comment by maehler** [comment]
Yes, that issue has been fixed. This is a different issue. What I'm trying to convey is that the underlying threshold changes, and that's why we see the update. If I click the slider the first time after changing the network, the view updates, but if I click it again, nothing happens (as is expected). Just try changing the network (take note of the number of nodes and edges), and then touching the slider without changing the threshold, and you'll hopefully see what I mean (compare the number of nodes and edges with what you had before).

**Comment by irusri** [comment]
Perfect! Now when we change the dataset, it will update the correct network. But if we click the slider nothing will happen. When we change the slider,  it will save as a cookie and it will be used when we reload the page or when we select a new dataset. Please let me know if you still get the same problem.

**Comment by maehler** [comment]
It's behaving differently now, but there is still something strange going on. Let's see if I can explain this clearly in text.

If I start with the genelist in my first comment, go to exNet, set the threshold to 10^-2 and select the AspWood network, I have a single connected component with 88 nodes and 2012 edges. If I then swap to the AspLeaf network, I see two connected components and 19 genes without any edges&mdash;in total 88 nodes and 164 edges.

This is where it starts to become tricky. The threshold seemingly hasn't changed&mdash;it still says 10^-2&mdash;but when I click the slider without changing its position, the threshold is changed to 10^-1 and I see 88 nodes and 265 edges.

---

Let's start over. I'm now looking at the AspWood network from before&mdash;threshold at 10^-2 and 88 nodes and 2012 edges. I swap to the AspLeaf network without changing the threshold. I see 88 nodes and 164 edges, and the threshold is set at 10^-2. Now I modify the threshold away from 10^-2, and then put it back to 10^-2, and then I suddenly have 88 nodes and 50 edges. Leaving the threshold at 10^-2, I go back to the AspWood network, and now I see 88 nodes and 719 edges, but I expect to see 2012 edges at that threshold given what I saw when I started. Clicking the slider changes the threshold to 10^-3 and I now see 88 nodes and 467 edges. Changing the slider to 10^-2 manually results in what I would expect: 88 nodes and 2012 edges.

**Comment by irusri** [comment]
Yes there was a an issue when we had decimal places to slider stepvalue .1 now I updated to 1. I think the issue has been fixed but please check once more. Thanks

**Comment by irusri** [comment]
1st use case: http://g.recordit.co/nh9AK9zN0d.gif
2nd use case: http://g.recordit.co/UGbdQCNwvM.gif

**Comment by maehler** [comment]
Ok, it seems like we're getting closer to a solution to these issues, but there are still some weird stuff going on. What you show in your screen captures is also what I see, but the issue with clicking the slider and the threshold changing is still there. In the video below, when I switch from one network to another and then click the slider, you can see that the threshold changes and the network is reloaded.

https://user-images.githubusercontent.com/2573608/114174983-b859a380-9939-11eb-9dd6-ef6a1bcf0dd0.mp4

This is a minor issue compared to the rest of it though, and it is possible to work around, albeit a bit annoying.

One other question arising from this is also why the number of nodes and edges in the networks is the same as before. This makes me question how the threshold is calculated. This is a question for later though, I would say. As long as things behave consistently, I'm not too worried.

**Comment by irusri** [comment]
When we change the dataset, the slider will also change according to the max and min values. So the handler will get different position compare to the previous position. This is the reason we get new value, when we click the handler. But it always uses the same p-value as displayed on the tool bar to render the network.  

For given 88 genes I get the following results.  
AspWood -> 10<sup>-1</sup>: 3400, 10<sup>-2</sup>: 1112, 10<sup>-3</sup>: 237
AspLeaf -> 10<sup>-1</sup>: 454, 10<sup>-2</sup>: 71, 10<sup>-3</sup>: 24

**Comment by maehler** [comment]
Yes, and those results are not the same as before you started working on this issue (see [my previous post](https://github.com/PlantGenIE/PlantGenIE/issues/82#issuecomment-816500720)).

That's fine that the positions would change, that's not the issue. I still consider this to be a bug, because you don't change the position of the slider, but still the threshold changes. This is highly unintuitive in my opinion. It's really great that the more important part of this issue has been fixed, but I would also like to see this being fixed as well.

**Comment by irusri** [comment]
Exactly we did not get the same results. because previously we passed decimal values. for example when we select slider to 10<sup>-2<sup> it represented the value from -1.5 to -2.4. Now we have 1 as slider step-value. 

Please check the handler issue once more. now it wont update when we click after selecting different datasets.

**Comment by maehler** [comment]
Awesome, now I think the behaviour is much more predictable than before. Great work!

There seems to be one more tiny thing though. When you first come in to the network visualisation, the first time you move the slider, nothing happens. This only seems to happen on the first move after a reload. Changing the network is still fine. Hopefully the video below demonstrates this.

https://user-images.githubusercontent.com/2573608/114187711-96b3e880-9948-11eb-97cc-29f684dc95bf.mp4

**Comment by irusri** [comment]
That issue also fixed. Please try once more. Thanks

**Comment by maehler** [comment]
Great, it seems to work like expected now! I'll close this issue. Thanks a lot!
