### ISSUE TITLE
Invalid genes can be added to the genelist

### ISSUE THREAD

**Issue by maehler** [PlantGenIE/PlantGenIE#83]
Let's say that I have *P. tremula* v2.2 as the selected species, and I search for a *P. trichocarpa* gene in the search field at the top of the page, I get a gene info page that says "Incorrect gene id Potri.T114800" (for example). However, there is still the possibility to add this non-existing gene to the active gene list by clicking the plus-icon on the page:

![Adding invalid genes to the genelist](https://user-images.githubusercontent.com/2573608/114026405-7e739900-9876-11eb-8246-89064bd1d79e.png)

If you started without any active genelist, it looks like you now have a non-empty genelist, but looking at it in the gene search tool shows that it is actually empty, but you have a single *P. trichocarpa* gene in the search field.

**Comment by irusri** [comment]
Here after we do not see the plus sign if we select wrong species. Please feel free to reopen if you still get the issue.
