### ISSUE TITLE
Add TF columns into gene_info table

### ISSUE THREAD

**Issue by irusri** [PlantGenIE/PlantGenIE#90]

**Comment by irusri** [comment]
Added additional column for TF in the transcript_info table. Here is the final results: http://g.recordit.co/58CgQdKSUJ.gif

**Comment by irusri** [comment]
`ALTER TABLE transcript_info MODIFY t_factor tinyint(1) AFTER transcript_end;`

**Comment by irusri** [comment]
`#!/bin/bash
DB_USER=''
DB_PASS='' '

declare  -A array='([piabi]="beta_plantgenie_piabi_v10" [pitae]="beta_plantgenie_pitae_v20" [pilam]="beta_plantgenie_pilam_v10" [psmen]="beta_plantgenie_psmen_v10" [gnmon]="beta_plantgenie_gnmon" [gibil]="beta_plantgenie_gibil_2016" [potri]="beta_plantgenie_potri_v31" [potra]="beta_plantgenie_potra_v22" [potrs]="beta_plantgenie_potrs_v11" [potrx]="beta_plantgenie_potrx_v10" [sapur]="beta_plantgenie_sapur_v10" [poeup]="beta_plantgenie_poeup_v20" [artha]="beta_plantgenie_artha_v11" [eugra]="beta_plantgenie_eugra_v20" [xasor]="beta_plantgenie_yellowhorn_xasor_v2f" [vivin]="beta_plantgenie_vivin_genoscope12x" [phpat]="beta_plantgenie_phpat_v33" [madom]="beta_plantgenie_madom_v20" [metru]="beta_plantgenie_metru_v10" [cusat]="beta_plantgenie_cusat_v10" [arann]="beta_plantgenie_arann_v10" [nitab]="beta_plantgenie_nitab_v45" [haimp]="beta_plantgenie_haimp" [migut]="beta_plantgenie_migut_v20" [casin]="beta_plantgenie_casin_v20" [maole]="beta_plantgenie_maole" [bevul]="beta_plantgenie_bevul_v12" [aqcoe]="beta_plantgenie_aqcoe_v31" [zomar]="beta_plantgenie_zomar_v22" [amtri]="beta_plantgenie_amtri_v10" [cikan]="beta_plantgenie_cikan_v10" [bepen]="beta_plantgenie_bepen_v14")'
for x in "${!array[@]}"; do
DB=${array[$SP]}
mysql --host=localhost  --user=$DB_USER --password=$DB_PASS --local_infile=1 --database=$DB <<EOFMYSQL
ALTER TABLE transcript_info MODIFY t_factor tinyint(1) AFTER transcript_end;
EOFMYSQL
done`

**Comment by irusri** [comment]
Finally update the TF table
```
UPDATE  transcript_info ti
left JOIN    TF t
ON      t.gene_id = ti.gene_id 
SET     ti.t_factor = (case when t.Family is null  then '0' else '1' end) 

```

**Comment by natstreet** [comment]
Great. This can be done for all species and then moved across to the main site.

One thing we could do, however, is to give the TF family name rather than ‘Yes’ as that would allow for more refined filtering. ‘No’ or ‘NA’ could then still be used when a gene is not a TF.

**Comment by irusri** [comment]
Sure, Now it works for all the species. When there is no TF data available in the database, it shows NA. Otherwise it shows No or Yes depending on the availability.

**Comment by irusri** [comment]
Sure, Now its shows Family name when there is TF gene available otherwise it shows NO. If we did not load data it shows NA. Does this makes sense?

**Comment by irusri** [comment]
Here is the example screenshot : http://g.recordit.co/Y3FqfrP96P.gif

**Comment by natstreet** [comment]
Perfect

**Comment by irusri** [comment]
I just pushed TF changes into the main site and update the log.

**Comment by irusri** [comment]
TF columns in now available on both sites and working fine.
