### ISSUE TITLE
Take away the PDF button from exHetamap

### ISSUE THREAD

**Issue by irusri** [PlantGenIE/PlantGenIE#94]

**Comment by irusri** [comment]
I just took away the PDF button from exHeatmap Tool until we have proper vector format export available.

**Comment by natstreet** [comment]
Confirmed and can be rolled over to the public site. 

We should leave an open issue to have a vector format export available if possible.

**Comment by irusri** [comment]
Sure! its done on both beta and production sites. New issue has been created #99

**Comment by irusri** [comment]
New issue has been created and we can close this issue.
