### ISSUE TITLE
Fixed external JBrowse link from gene pages

### ISSUE THREAD

**Issue by irusri** [PlantGenIE/PlantGenIE#97]

**Comment by irusri** [comment]
We just need to test before we close the issue. It should work in both beta and production sites.

**Comment by natstreet** [comment]
Confirmed, but please put (JBrowse) next to the link so the user knows where that will take them. Note: this is not an external link.

**Comment by irusri** [comment]
Thanks for the comment! I just fixed this on both beta and production version.
